version: '3.9'

services:
  myapp:
    build:
      context: script
      dockerfile: Dockerfile
    volumes:
      - .:/app:Z   # bind current directory to /app in container
    working_dir: /app
    tty: true    # optional, keeps container running for interactive shell
